app:
  display:
    # The display resolution of the application.
    # Note: This setting is not magical; Changing it will not necessarily achieve the results
    # you expect.
    width: 1920
    height: 1080
  ui:
    # Time in seconds it takes for the training panel to appear or disappear
    trainingPanelTransitionDuration: 0.3
